services:
  # Override web service to connect to local LMStudio
  web:
    environment:
      - LMSTUDIO_API_URL=http://host.docker.internal:1234/v1
      - LMSTUDIO_MODEL=llama-3.2-1b-instruct
      - LLM_TEMPERATURE=0.3
      - LLM_MAX_TOKENS=2048
    extra_hosts:
      - "host.docker.internal:host-gateway"
